[general]
live_config_reload = true
import = [
    "~/.config/alacritty/themes/themes/inferno.toml",
]

[env]
TERM = "alacritty"

[window]
opacity = 1
dynamic_padding = false

[window.padding]
x = 5
y = 5

[font]
size = 14

[font.normal]
family = "Terminess Nerd Font"
style = "Regular"

[font.bold]
style = "Bold"

[font.italic]
style = "Italic"

[font.bold_italic]
style = "Bold Italic"

[scrolling]
history = 10000
multiplier = 3

[cursor]
blink_interval = 500
unfocused_hollow = true

[cursor.style]
shape = "Block"
blinking = "Off"

[selection]
save_to_clipboard = true

[[mouse.bindings]]
mouse = "Right"
action = "Paste"
